#define Color_Bot 			0xFF8600FF
#define Color_Blanco 		0xFFFFFFFF
#define Color_Azul      	0x0086FFFF
#define ME_COLOR        	0x00A0FFFF
#define COLOR_ME            0x00A0FFFF
#define TEAM_RADIO_COLOR    0x15FF96FF
#define Color_Rojo 			0xFF0000FF
/* Colores Habla */
#define ColorH 0xFFFFFFFF
#define ColorH2 0xDCDBDAFF
#define ColorH3 0xB7B7B6FF
#define ColorH4 0x797979FF
#define ColorH5 0x393A3BFF